package com.nsdev.atlassearch.repository;

import com.nsdev.atlassearch.domain.Hotel;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.querydsl.QuerydslPredicateExecutor;
import org.springframework.stereotype.Repository;

/**
 * Data Access Layer for the Hotel entity.
 * <p>
 * This interface extends {@link JpaRepository} for standard CRUD operations and
 * {@link QuerydslPredicateExecutor} to enable dynamic, type-safe filtering capabilities.
 * </p>
 * <p>
 * By extending {@code QuerydslPredicateExecutor}, we can pass {@code Predicate} objects
 * generated by the Service layer directly to the database query, avoiding complex
 * {@code CriteriaBuilder} boilerplate or brittle String-based HQL.
 * </p>
 */
@Repository
public interface HotelRepository extends JpaRepository<Hotel, Long>, QuerydslPredicateExecutor<Hotel> {
}