server:
  servlet:
    context-path: /atlas-search
spring:
  application:
    name: atlas-search
  datasource:
    url: jdbc:postgresql://localhost:5432/atlas_db
    username: admin
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

  observations:
    annotations:
      enabled: true
    key-values:
      application: ${spring.application.name}

  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true

  tracing:
    sampling:
      probability: 1.0

  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces