apiVersion: apps/v1
kind: Deployment
metadata:
  name: atlas-search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atlas-search
  template:
    metadata:
      labels:
        app: atlas-search
    spec:
      containers:
        - name: atlas-search
          image: atlas-search:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/atlas_db
            - name: SPRING_DATASOURCE_USERNAME
              value: atlas_user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

            - name: SPRING_DATA_REDIS_HOST
              value: redis
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"

            - name: SPRING_PROFILES_ACTIVE
              value: "default"

---
apiVersion: v1
kind: Service
metadata:
  name: atlas-search
  labels:
    app: atlas-search
spec:
  type: NodePort
  selector:
    app: atlas-search
  ports:
    - name: web
      port: 8080
      targetPort: 8080
      nodePort: 30080